# Generated by Django 4.2.16 on 2024-11-22 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionmovie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
